# Etapa 1: Build
FROM node:18-alpine AS builder
WORKDIR /app

# ---- DECLARAR LOS ARG PARA RECIBIR ENVS ----
ARG VITE_AUTH0_DOMAIN
ARG VITE_AUTH0_CLIENT_ID
ARG VITE_AUTH0_AUDIENCE
ARG VITE_AUTH0_CALLBACK_URL
ARG VITE_API_BASE_URL
ARG VITE_API_USER_BASE_URL

# ---- EXPORTARLOS COMO ENV PARA QUE VITE LOS LEA ----
ENV VITE_AUTH0_DOMAIN=$VITE_AUTH0_DOMAIN
ENV VITE_AUTH0_CLIENT_ID=$VITE_AUTH0_CLIENT_ID
ENV VITE_AUTH0_AUDIENCE=$VITE_AUTH0_AUDIENCE
ENV VITE_AUTH0_CALLBACK_URL=$VITE_AUTH0_CALLBACK_URL
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_API_USER_BASE_URL=$VITE_API_USER_BASE_URL

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Etapa 2: Servir build estático con NGINX
FROM nginx:1.27-alpine

COPY --from=builder /app/dist /usr/share/nginx/html

# Remover config default
RUN rm /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
