events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    server_tokens off;
    charset       utf-8;

    server {
        listen 80;
         server_name _;

        # Ruta a los archivos estáticos de la UI
        root /usr/share/nginx/html;
        index index.html;

        # Manejo de archivos JS
        location ~* \.js$ {
            add_header Content-Type application/javascript;
            try_files $uri =404;
        }

        # Manejo de archivos CSS
        location ~* \.css$ {
            add_header Content-Type text/css;
            try_files $uri =404;
        }

        # Archivos de imágenes, fuentes y otros
        location ~* \.(png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf|eot)$ {
            try_files $uri =404;
            access_log off;
            log_not_found off;
        }

        # SPA routing: todas las rutas van a index.html
        location / {
            try_files $uri /index.html;
        }
    }
}