name: UI CD - DEV

on:
  push:
    branches: [ "group-2-dev","fixes" ]

permissions:
  contents: write
  packages: write
  id-token: write
jobs:
  deploy-ui-dev:
    uses: IngsisPrintScript/workflows-and-actions/.github/workflows/build-ui.yaml@main
    with:
      environment: development
      service_name: ui
      image_route: ghcr.io/ingsisprintscript/printscript-ui:dev
    secrets: inherit
