name: UI CI - DEV

on:
  push:
    branches:
      - group-2-dev

jobs:
  ui-dev:
    uses: IngsisPrintScript/workflows-and-actions/.github/workflows/build-ui.yaml@main
    with:
      image-name: printscript-ui
      image-tag: dev
      compose-service: ui
      compose-file: docker-compose.dev.yml
      server-path: /home/ingsis2/infra-ingsis
    secrets: inherit