name: UI CI

on:
  push:
    branches: [ "dev", "main" ]

jobs:
  call-ui-cd:
    uses: IngsisPrintScript/workflows-and-actions/.github/workflows/build-ui.yaml@main
    with:
      image-name: printscript-ui
    secrets: inherit
