name: UI CI

on:
  push:
    branches:
      - group-2-main

permissions:
  contents: write
  packages: write

jobs:
  call-ui-cd:
    uses: IngsisPrintScript/workflows-and-actions/.github/workflows/build-ui.yaml@main
    with:
      image-name: printscript-ui
    secrets: inherit